image: python:3.5

before_script:
  - apt-get update -qq && apt-get install -y libpq-dev python-dev
  - pip install --upgrade -r requirements.txt

pytest:
  script:
    - py.test -n2 --tb=native weiqi