image: python:3.5

before_script:
  - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
  - dpkg -i hugo*.deb
  - pip install --upgrade -r requirements.txt

pytest:
  script:
    - py.test --cov=weiqi --tb=native weiqi

blog:
  only:
    - master
  script:
    - cd blog && hugo && mv public ../public
  artifacts:
    paths:
      - public